#!/usr/bin/env python3
"""Generate src/display/EmbeddedExtraFonts.h: extra selectable Latin reader/UI faces.

Each face is rendered for ASCII 32..126 (enough for English books and the UI) into a single combined
header with a full-size and a ~70% variant, exposed as a table the reader/UI index at runtime. This
is intentionally simpler than the GhostScript serif pipeline (no European accent slots) so the data
stays small and the generator is self-contained (PIL only).
"""

from __future__ import annotations

import pathlib

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "display" / "EmbeddedExtraFonts.h"
FONT_ROOT = pathlib.Path("/tmp/claude-0/-home-user-rsvpnano/"
                         "5c08be45-319d-54a1-8784-f3a0cd0a30c1/scratchpad/uifonts")

FIRST_CHAR = 32
LAST_CHAR = 126
TARGET_FULL_HEIGHT = 62        # match the serif reader cell so line heights line up
ALPHA_THRESHOLD = 16
CANVAS_W = 200
CANVAS_H = 200
BASELINE_Y = 130
ORIGIN_X = 20

# display name, ttf path, C identifier. (User picked Gluten; add more here to offer more faces.)
FONTS = [
    ("Gluten", FONT_ROOT / "Gluten/static/Gluten-Regular.ttf", "Gluten"),
]


def vertical_extent(font):
    """Global (top, bottom) inked rows across all glyphs."""
    top, bot = 10**9, -1
    for c in range(FIRST_CHAR, LAST_CHAR + 1):
        img = Image.new("L", (CANVAS_W, CANVAS_H), 255)
        d = ImageDraw.Draw(img)
        d.text((ORIGIN_X, BASELINE_Y), chr(c), fill=0, font=font, anchor="ls")
        px = img.load()
        for y in range(CANVAS_H):
            if any(255 - px[x, y] > ALPHA_THRESHOLD for x in range(CANVAS_W)):
                top = min(top, y)
                bot = max(bot, y)
    return (top, bot) if bot >= 0 else (BASELINE_Y - 1, BASELINE_Y)


def fit_point_size(path, target_height):
    best, err = 40, 10**9
    for size in range(24, 110):
        t, b = vertical_extent(ImageFont.truetype(path, size))
        e = abs((b - t + 1) - target_height)
        if e < err:
            best, err = size, e
    return best


def build_variant(path, point_size):
    font = ImageFont.truetype(path, point_size)
    top, bot = vertical_extent(font)
    height = bot - top + 1
    bitmap_bytes: list[int] = []
    glyphs: list[str] = []
    for c in range(FIRST_CHAR, LAST_CHAR + 1):
        img = Image.new("L", (CANVAS_W, CANVAS_H), 255)
        d = ImageDraw.Draw(img)
        d.text((ORIGIN_X, BASELINE_Y), chr(c), fill=0, font=font, anchor="ls")
        px = img.load()
        minx, maxx = CANVAS_W, -1
        for y in range(top, bot + 1):
            for x in range(CANVAS_W):
                if 255 - px[x, y] > ALPHA_THRESHOLD:
                    minx = min(minx, x)
                    maxx = max(maxx, x)
        advance = max(1, int(round(font.getlength(chr(c)))))
        offset = len(bitmap_bytes)
        if maxx < minx:
            glyphs.append(f"    {{{offset}, 0, 0, {advance}}},")
            continue
        width = maxx - minx + 1
        for y in range(top, bot + 1):
            for x in range(minx, maxx + 1):
                a = 255 - px[x, y]
                bitmap_bytes.append(a if a > ALPHA_THRESHOLD else 0)
        glyphs.append(f"    {{{offset}, {minx - ORIGIN_X}, {width}, {advance}}},")
    return height, bitmap_bytes, glyphs


def emit_array(lines, name, data):
    lines.append(f"static const uint8_t {name}[] PROGMEM = {{")
    for off in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"{v:3d}" for v in data[off:off + 16]) + ",")
    if not data:
        lines.append("    0,")
    lines.append("};")


def main() -> None:
    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Generated by tools/generate_extra_fonts.py. Extra selectable Latin faces (ASCII 32..126)",
        "// for the reader (book font) and the UI font, with a full and a ~70% size variant each.",
        "",
        "struct ExtraGlyph {",
        "  uint32_t bitmapOffset;",
        "  int8_t xOffset;",
        "  uint8_t width;",
        "  uint8_t xAdvance;",
        "};",
        "",
        "struct ExtraFontFace {",
        "  const uint8_t *bitmaps;",
        "  const ExtraGlyph *glyphs;",
        "  uint8_t firstChar;",
        "  uint8_t lastChar;",
        "  uint8_t height;",
        "};",
        "",
        f"constexpr uint8_t kExtraFontFirstChar = {FIRST_CHAR};",
        f"constexpr uint8_t kExtraFontLastChar = {LAST_CHAR};",
        "",
    ]

    faces = []  # (ident, full_height, seventy_height)
    names = []
    for name, path, ident in FONTS:
        full_pt = fit_point_size(str(path), TARGET_FULL_HEIGHT)
        seventy_pt = max(12, int(round(full_pt * 0.7)))
        fh, fbytes, fglyphs = build_variant(str(path), full_pt)
        sh, sbytes, sglyphs = build_variant(str(path), seventy_pt)
        print(f"{name}: full {full_pt}pt h{fh} ({len(fbytes)//1024}KB), "
              f"70 {seventy_pt}pt h{sh} ({len(sbytes)//1024}KB)")
        emit_array(lines, f"kExtraBitmaps_{ident}_full", fbytes)
        lines.append(f"static const ExtraGlyph kExtraGlyphs_{ident}_full[] PROGMEM = {{")
        lines.extend(fglyphs)
        lines.append("};")
        emit_array(lines, f"kExtraBitmaps_{ident}_s70", sbytes)
        lines.append(f"static const ExtraGlyph kExtraGlyphs_{ident}_s70[] PROGMEM = {{")
        lines.extend(sglyphs)
        lines.append("};")
        lines.append("")
        faces.append((ident, fh, sh))
        names.append(name)

    lines.append("// [font][0 = full, 1 = ~70%]")
    lines.append("static const ExtraFontFace kExtraFontFaces[][2] = {")
    for ident, fh, sh in faces:
        lines.append(
            f"    {{{{kExtraBitmaps_{ident}_full, kExtraGlyphs_{ident}_full, kExtraFontFirstChar, "
            f"kExtraFontLastChar, {fh}}},")
        lines.append(
            f"     {{kExtraBitmaps_{ident}_s70, kExtraGlyphs_{ident}_s70, kExtraFontFirstChar, "
            f"kExtraFontLastChar, {sh}}}}},")
    lines.append("};")
    lines.append(f"constexpr uint8_t kExtraFontCount = {len(FONTS)};")
    lines.append("static const char *const kExtraFontNames[] = {")
    for n in names:
        lines.append(f"    \"{n}\",")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
