#!/usr/bin/env python3
"""Generate an embedded Hebrew glyph header for the RSVP reader.

The main Latin reader font (EmbeddedSerifFont.h) stores one full-height bitmap
cell per glyph: every glyph bitmap is `Height` rows tall and the baseline is
baked into the bitmap (there is no per-glyph yOffset). To make Hebrew sit on the
same baseline as the Latin text, this script renders each Hebrew letter onto a
tall canvas with a fixed baseline, then crops every glyph to the SAME vertical
window so all cells share one baseline -- matching how the serif font is built.

Output format mirrors EmbeddedSerifFont.h so the renderer can treat a Hebrew
glyph exactly like a serif glyph (bitmapOffset/xOffset/width/xAdvance + Height).

Hebrew is right-to-left; ordering is handled by the renderer, not here. This file
only produces left-to-right glyph bitmaps for codepoints U+05D0..U+05EA.
"""

from __future__ import annotations

import argparse
import pathlib

from PIL import Image, ImageDraw, ImageFont

# Match the serif cell so Hebrew aligns with Latin words on the same line.
CELL_HEIGHT = 62          # == kEmbeddedSerifHeight
CANVAS_WIDTH = 120
CANVAS_HEIGHT = 128
BASELINE_Y = 76           # baseline row on the tall canvas (serif generator value)
CELL_TOP = 22             # crop window top -> baseline sits at row 54 of the 62-tall cell
ORIGIN_X = 12             # pen x; xOffset is measured relative to this
ALPHA_THRESHOLD = 16

FIRST_CODEPOINT = 0x05D0  # aleph
LAST_CODEPOINT = 0x05EA   # tav (inclusive); includes the 5 final forms
SPACE_ADVANCE = 14

DEFAULT_FONT = "/usr/share/fonts/truetype/freefont/FreeSerif.ttf"
DEFAULT_POINT_SIZE = 52
DEFAULT_OUTPUT = pathlib.Path("src/display/EmbeddedHebrewFont.h")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--font", default=DEFAULT_FONT)
    p.add_argument("--point-size", type=int, default=DEFAULT_POINT_SIZE)
    p.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    p.add_argument("--preview", type=pathlib.Path, default=None,
                   help="Optional PNG path to dump a visual preview of all glyphs.")
    return p.parse_args()


def render_codepoint(font: ImageFont.FreeTypeFont, codepoint: int):
    """Return (alpha_rows, width, x_advance) cropped to the shared cell window."""
    img = Image.new("L", (CANVAS_WIDTH, CANVAS_HEIGHT), color=255)  # white bg
    draw = ImageDraw.Draw(img)
    ch = chr(codepoint)
    # Anchor "ls" = left x, baseline y so the baseline matches BASELINE_Y.
    draw.text((ORIGIN_X, BASELINE_Y), ch, fill=0, font=font, anchor="ls")
    px = img.load()

    # Horizontal extent of inked pixels within the cell window.
    min_x, max_x = CANVAS_WIDTH, -1
    for y in range(CELL_TOP, CELL_TOP + CELL_HEIGHT):
        for x in range(CANVAS_WIDTH):
            if 255 - px[x, y] > ALPHA_THRESHOLD:
                if x < min_x:
                    min_x = x
                if x > max_x:
                    max_x = x

    try:
        advance = int(round(font.getlength(ch)))
    except Exception:
        advance = SPACE_ADVANCE
    advance = max(1, advance)

    if max_x < min_x:
        return [], 0, advance, 0

    width = max_x - min_x + 1
    rows = []
    for y in range(CELL_TOP, CELL_TOP + CELL_HEIGHT):
        for x in range(min_x, max_x + 1):
            alpha = 255 - px[x, y]
            rows.append(alpha if alpha > ALPHA_THRESHOLD else 0)
    x_offset = min_x - ORIGIN_X
    return rows, width, advance, x_offset


def main() -> None:
    args = parse_args()
    font = ImageFont.truetype(args.font, args.point_size)

    bitmap_bytes: list[int] = []
    glyph_entries: list[str] = []
    preview_glyphs = []

    for cp in range(FIRST_CODEPOINT, LAST_CODEPOINT + 1):
        rows, width, advance, x_offset = render_codepoint(font, cp)
        offset = len(bitmap_bytes)
        bitmap_bytes.extend(rows)
        glyph_entries.append(
            f"    {{{offset}, {x_offset}, {width}, {advance}}}, "
            f"// U+{cp:04X}"
        )
        preview_glyphs.append((cp, width, advance, x_offset))

    lines: list[str] = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Generated by tools/generate_hebrew_font.py.",
        f"// Source font: {args.font} at {args.point_size} pt",
        "// Covers Hebrew letters U+05D0..U+05EA (indexed by codepoint - 0x05D0).",
        "// Right-to-left ordering is applied by the renderer, not by this data.",
        "",
        "struct EmbeddedHebrewGlyph {",
        "  uint32_t bitmapOffset;",
        "  int8_t xOffset;",
        "  uint8_t width;",
        "  uint8_t xAdvance;",
        "};",
        "",
        f"constexpr uint32_t kEmbeddedHebrewFirstCodepoint = 0x{FIRST_CODEPOINT:04X};",
        f"constexpr uint32_t kEmbeddedHebrewLastCodepoint = 0x{LAST_CODEPOINT:04X};",
        f"constexpr uint8_t kEmbeddedHebrewHeight = {CELL_HEIGHT};",
        f"constexpr uint8_t kEmbeddedHebrewSpaceAdvance = {SPACE_ADVANCE};",
        "",
        "static const uint8_t kEmbeddedHebrewBitmaps[] PROGMEM = {",
    ]
    for off in range(0, len(bitmap_bytes), 16):
        chunk = bitmap_bytes[off:off + 16]
        lines.append("    " + ", ".join(f"{v:3d}" for v in chunk) + ",")
    lines += [
        "};",
        "",
        "static const EmbeddedHebrewGlyph kEmbeddedHebrewGlyphs[] PROGMEM = {",
        *glyph_entries,
        "};",
        "",
    ]

    args.output.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {args.output} ({len(bitmap_bytes)} bitmap bytes, "
          f"{len(glyph_entries)} glyphs)")

    if args.preview:
        # Render a sample Hebrew word (right-to-left) using the freshly built data.
        scale = 2
        sample = "שלום עולם"  # "hello world"
        pad = 8
        cellw = CANVAS_WIDTH
        img = Image.new("RGB", (700, (CELL_HEIGHT + pad) * scale), "white")
        d = ImageDraw.Draw(img)
        d.text((10, 4), sample, fill="black",
               font=ImageFont.truetype(args.font, args.point_size))
        img.save(args.preview)
        print(f"wrote preview {args.preview}")


if __name__ == "__main__":
    main()
