#!/usr/bin/env python3
"""Generate src/display/EmbeddedPoopik.h from the Poopik frame PNGs in docs/poopik/.

The pet (Poopik) is pixel art with a transparent background. Each frame is stored as an indexed
bitmap: a shared palette (RGB565 + alpha) plus one palette-index byte per pixel. Palette index 0 is
always the fully transparent entry, so the renderer can skip it and let the themed background show.

Reads:  docs/poopik/purring_*.png   (and, when present, docs/poopik/angry_*.png)
Writes: src/display/EmbeddedPoopik.h
"""

from __future__ import annotations

import glob
import os
import pathlib
import re

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "docs" / "poopik"
OUT = ROOT / "src" / "display" / "EmbeddedPoopik.h"


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def natural_key(path: str):
    nums = re.findall(r"\d+", os.path.basename(path))
    return int(nums[-1]) if nums else 0


def load_anim(prefix: str):
    files = sorted(glob.glob(str(SRC_DIR / f"{prefix}_*.png")), key=natural_key)
    return [Image.open(f).convert("RGBA") for f in files]


def main() -> None:
    anims = {}
    for name in ("purring", "angry"):
        frames = load_anim(name)
        if frames:
            anims[name] = frames

    if not anims:
        raise SystemExit(f"no Poopik PNGs found in {SRC_DIR}")

    # The firmware always references a kPoopikAngry* symbol. If no angry art exists yet, emit a
    # placeholder (a copy of the first purring frame); add docs/poopik/angry_*.png to replace it.
    has_angry_art = "angry" in anims
    if not has_angry_art:
        base = anims.get("purring") or next(iter(anims.values()))
        anims["angry"] = [base[0].copy()]

    # Uniform canvas across every frame so the cat never jumps.
    width = max(fr.width for frames in anims.values() for fr in frames)
    height = max(fr.height for frames in anims.values() for fr in frames)

    # Build a shared palette. Index 0 = transparent.
    palette = [(0, 0, 0, 0)]
    palette_index = {(0, 0, 0, 0): 0}

    def index_for(px):
        r, g, b, a = px
        if a == 0:
            return 0
        key = (r, g, b, 255)
        if key not in palette_index:
            palette_index[key] = len(palette)
            palette.append(key)
        return palette_index[key]

    def frame_indices(fr: Image.Image):
        # Center the frame on the uniform canvas.
        canvas = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        canvas.alpha_composite(fr, ((width - fr.width) // 2, (height - fr.height) // 2))
        px = canvas.load()
        out = []
        for y in range(height):
            for x in range(width):
                out.append(index_for(px[x, y]))
        return out

    anim_data = {name: [frame_indices(fr) for fr in frames] for name, frames in anims.items()}

    if len(palette) > 255:
        raise SystemExit(f"too many colors for a byte palette: {len(palette)}")

    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Generated by tools/generate_poopik_sprites.py from docs/poopik/*.png.",
        "// Indexed pixel art: kPoopikPalette565[i]/kPoopikPaletteAlpha[i] give each palette entry;",
        "// palette index 0 is fully transparent (skip it so the themed background shows through).",
        "",
        f"constexpr uint8_t kPoopikWidth = {width};",
        f"constexpr uint8_t kPoopikHeight = {height};",
        f"constexpr bool kPoopikHasAngryArt = {'true' if has_angry_art else 'false'};",
        "",
        f"static const uint16_t kPoopikPalette565[{len(palette)}] PROGMEM = {{",
        "    " + ", ".join(f"0x{rgb565(r, g, b):04X}" for (r, g, b, a) in palette),
        "};",
        f"static const uint8_t kPoopikPaletteAlpha[{len(palette)}] PROGMEM = {{",
        "    " + ", ".join(str(a) for (r, g, b, a) in palette),
        "};",
        "",
    ]

    for name, frames in anim_data.items():
        cname = name.capitalize()
        lines.append(f"constexpr uint8_t kPoopik{cname}FrameCount = {len(frames)};")
        lines.append(
            f"static const uint8_t kPoopik{cname}Frames[{len(frames)}]"
            f"[{width * height}] PROGMEM = {{"
        )
        for fr in frames:
            row = ", ".join(str(v) for v in fr)
            lines.append("    {" + row + "},")
        lines.append("};")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT}: {width}x{height}, palette {len(palette)}, "
          + ", ".join(f"{n}={len(f)}f" for n, f in anim_data.items()))


if __name__ == "__main__":
    main()
